### ISSUE TITLE
Kamu 2.0 17.3

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/finpar#5]
Kansan Muisti will release version 2.0 of the database on March 17. I wonder if this would imply changes to the R interface. To be checked.

**Comment by jlehtoma** [comment]
Shouldn't affect things much since the current version is built on top of the dev version. Having said that, I haven't checked lately if the API has changed. Then there isn't much implemented yet anyways.

**Comment by jlehtoma** [comment]
Well, the URL may change so let's keep this open for the time being.

**Comment by antagomir** [comment]
"rajapinnan osoitteen vois laittaa suoraan kansanmuisti.fi"

**Comment by antagomir** [comment]
Done. Works fine.
