### ISSUE TITLE
README vs. vigenette

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/finpar#8]
I suggest keeping root folder README minimal, and moving all R code etc. in the vignette. Following the conventions used in the other rOpenGov packages so far (like this: https://github.com/rOpenGov/sorvi). Not critical and can be skipped but if agreed I can do this.

**Comment by jlehtoma** [comment]
Fine by me!

**Comment by antagomir** [comment]
Done. To be merged in master soon.
